=== wanikirtesh/anyMocker/request_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://sbn.com/request.schema.json",
  "title": "Requests",
  "description": "Requests for mock server",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "description": "unique name for request",
        "type": "string"
      },
      "url": {
        "description": "request url",
        "type": "string"
      },
      "method": {
        "description": "request method",
        "type": "string"
      },
      "processor": {
        "description": "Bean name of request Processor",
        "type": "string"
      },
      "download": {
        "description": "need fixture download for response?",
        "type": "boolean"
      },
      "meta": {
        "description": "additional information <string:string> object for support",
        "type": "object"
      },
      "queryParam": {
        "description": "query parameter list",
        "type": "array",
        "items": {
          "type": "string"
        },
        "uniqueItems": true
      },
      "pathParam": {
        "description": "path parameter list",
        "type": "array",
        "items": {
          "type": "string"
        },
        "uniqueItems": true
      }
    },
    "required": [
      "name",
      "url",
      "method",
      "processor"
    ]
  }
}

=== wanikirtesh/anyMocker/requests/NGI.json
[
  {
    "name": "statisticsCorrelation",
    "url":  "/statisticsCorrelation/{clientCode}/{propertyCode}/{statisticsCorrelationId}",
    "method": "GET",
    "queryParam": [],
    "pathParam": ["clientCode","propertyCode","statisticsCorrelationId"],
    "processor": "NGI",
    "download": true,
    "meta": {
      "pages": false
    }
  },
  {
    "name": "activitiesHotel",
    "url": "/api/v1/activities/hotel/{clientCode}/{propertyCode}/{correlationId}",
    "method": "GET",
    "queryParam": ["size","page"],
    "pathParam": ["clientCode","propertyCode","correlationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "correlation": true,
      "size": 500
    }
  },
  {
    "name": "groups",
    "url": "/api/v1/groups/{clientCode}/{propertyCode}/correlated/{statisticsCorrelationId}",
    "method": "GET",
    "queryParam": ["size","page"],
    "pathParam": ["clientCode","propertyCode","statisticsCorrelationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "size": 100
    }
  },

  {
    "name": "marketSegmentAndRateCodeAndAMSByClientCodeAndPropertyCode",
    "url":  "/nucleusOccupancySummaryAMS/findMarketSegmentAndRateCodeAndAMSByClientCodeAndPropertyCode",
    "method": "GET",
    "queryParam": ["clientCode","propertyCode","correlationId","format"],
    "pathParam": [],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": false
    }
  },

  {
    "name": "nucleusStatisticsCorrelations",
    "url":  "/nucleusStatisticsCorrelations/{statisticsCorrelationId}",
    "method": "GET",
    "queryParam": [],
    "pathParam": ["statisticsCorrelationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": false
    }
  },
  {
    "name": "reservations",
    "url":  "/getReservations",
    "method": "GET",
    "queryParam": ["clientCode","propertyCode","statisticsCorrelationId","size","page"],
    "pathParam": [],
    "processor": "OK_ONLY",
    "meta": {
      "pages": true,
      "size": 100
    }
  },
  {
    "name": "roomTypeCodes",
    "url":  "/api/v1/activities/roomtype/{clientCode}/{propertyCode}/{statisticsCorrelationId}/capacity/roomtypecodes",
    "method": "GET",
    "queryParam": [],
    "pathParam": ["clientCode","propertyCode","statisticsCorrelationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": false,
      "size": 500
    }
  },
  {
    "name": "reservations2",
    "url":  "/api/v1/reservations/{clientCode}/{propertyCode}/correlated/{statisticsCorrelationId}",
    "method": "GET",
    "queryParam": ["page","size"],
    "pathParam": ["clientCode","propertyCode","statisticsCorrelationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "size": 500
    }
  },
  {
    "name":  "roomTypeMarketSegmentActivities",
    "url":  "/api/v1/activities/roomtypemarketsegment/{clientCode}/{propertyCode}/{correlationId}",
    "method": "GET",
    "queryParam": ["page","size"],
    "pathParam": ["clientCode","propertyCode","correlationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "size": 500,
      "correlation": true
    }
  },
  {
    "name": "roomTypeMarketSegmentHotelActivities",
    "url":  "/api/v1/activities/roomtypemarketsegment/{clientCode}/{propertyCode}/{correlationId}/hotel",
    "method": "GET",
    "queryParam": ["page","size"],
    "pathParam": ["clientCode","propertyCode","correlationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "size": 500,
      "correlation": true
    }
  },
  {
    "name": "roomTypeMarketSegmentProvidedActivities",
    "url":  "/api/v1/activities/roomtypemarketsegment/{clientCode}/{propertyCode}/{correlationId}/provided",
    "method": "GET",
    "queryParam": ["page","size"],
    "pathParam": ["clientCode","propertyCode","correlationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "size": 500,
      "correlation": true
    }
  },

  {
    "name": "roomTypes",
    "url":  "/api/v1/activities/roomtype/{clientCode}/{propertyCode}/{correlationId}",
    "method": "GET",
    "queryParam": ["page","size","startDate"],
    "pathParam": ["clientCode","propertyCode","correlationId"],
    "processor": "NGI",
    "download":true,
    "meta": {
      "pages": true,
      "size": 500,
      "correlation": true
    }
  },
  {
    "name": "mockAnalyticalMarketServiceRemapReservationAndOccupancy",
    "url":  "/analyticalMarketService/remapReservationAndOccupancy",
    "method": "POST",
    "queryParam": [],
    "pathParam": [],
    "processor": "OK_ONLY",
    "meta": {
      "pages": false,
      "size": 500,
      "correlation": false,
      "g3CallBack": "callBack1"
    }
  },
    {
    "name": "/analyticalMarketService/deleteByProperty",
    "url": "/analyticalMarketService/deleteByProperty",
    "method": "DELETE",
    "queryParam": [],
    "pathParam": ["clientCode","propertyCode"],
    "processor": "OK_ONLY"
  },
  {
    "name": "/analyticalMarketService/populate",
    "url": "/analyticalMarketService/populate",
    "method": "POST",
    "queryParam": [],
    "pathParam": ["clientCode","propertyCode"],
    "processor": "NGI",
    "meta": {
      "g3CallBack": "callG3"
    }
  }

]
